from django.urls import path

from api.auth_views import LoginView, LogoutView, MeView, SignupView
from api.views import (
    AnalysisPlanApproveView,
    AnalysisPlanDetailView,
    AnalysisPlanGenerateView,
    AnalysisPlanListCreateView,
    AnalysisPlanRunView,
    AnalysisResultDetailView,
    ArchitectureApproveView,
    ArchitectureGenerateView,
    ArchitectureUpdateView,
    BlueprintApproveView,
    BlueprintGenerateView,
    BlueprintUpdateView,
    BuildPromptGenerateView,
    BusinessLogicApproveView,
    BusinessLogicGenerateView,
    BusinessLogicUpdateView,
    ConversationCreateView,
    ConversationDetailView,
    ConversationMessageView,
    DataBriefApproveView,
    DataBriefGenerateView,
    DataBriefUpdateView,
    DataQualityApproveView,
    DataQualityCheckView,
    DataQualityObserveView,
    DataQualityProposeRulesView,
    DataQualityView,
    DashboardApproveView,
    DashboardBuildPromptView,
    DashboardGenerateView,
    DashboardView,
    DatasetDetailView,
    DatasetListCreateView,
    DatasetProfileView,
    DataLineageView,
    DataProgressView,
    DataReadinessView,
    DiscoveryAnswersView,
    HealthView,
    InsightAcceptView,
    InsightGenerateView,
    JobDetailView,
    MetricApproveView,
    MetricDetailView,
    MetricGenerateView,
    MetricListView,
    MetricValidateView,
    ProgressView,
    ProjectDetailView,
    ProjectListCreateView,
    ProposalApproveView,
    ProposalRejectView,
    QueryDetailView,
    QueryExecuteView,
    QueryGenerateSqlView,
    QueryListCreateView,
    QueryMarkReviewedView,
    QueryPlanApproveView,
    QueryPlanUpdateView,
    QueryReviewView,
    ReviewPromptGenerateView,
    RoadmapApproveView,
    ShipChecklistView,
    RoadmapGenerateView,
    RoadmapTaskView,
    RoadmapUpdateView,
    SourceInterpretationApproveView,
    SourceInterpretationGenerateView,
    SourceInterpretationUpdateView,
    TransformationApproveView,
    TransformationGenerateView,
    TransformationPreviewView,
    TransformationView,
)

urlpatterns = [
    path("health/", HealthView.as_view(), name="health"),
    path("auth/signup/", SignupView.as_view(), name="auth-signup"),
    path("auth/login/", LoginView.as_view(), name="auth-login"),
    path("auth/logout/", LogoutView.as_view(), name="auth-logout"),
    path("auth/me/", MeView.as_view(), name="auth-me"),
    path("projects/", ProjectListCreateView.as_view(), name="project-list-create"),
    path("projects/<slug:slug>/", ProjectDetailView.as_view(), name="project-detail"),
    path(
        "projects/<slug:slug>/discovery/answers/",
        DiscoveryAnswersView.as_view(),
        name="discovery-answers",
    ),
    path(
        "projects/<slug:slug>/blueprint/generate/",
        BlueprintGenerateView.as_view(),
        name="blueprint-generate",
    ),
    path(
        "projects/<slug:slug>/blueprint/",
        BlueprintUpdateView.as_view(),
        name="blueprint-update",
    ),
    path(
        "projects/<slug:slug>/blueprint/approve/",
        BlueprintApproveView.as_view(),
        name="blueprint-approve",
    ),
    path(
        "projects/<slug:slug>/business-logic/generate/",
        BusinessLogicGenerateView.as_view(),
        name="business-logic-generate",
    ),
    path(
        "projects/<slug:slug>/business-logic/",
        BusinessLogicUpdateView.as_view(),
        name="business-logic-update",
    ),
    path(
        "projects/<slug:slug>/business-logic/approve/",
        BusinessLogicApproveView.as_view(),
        name="business-logic-approve",
    ),
    path(
        "projects/<slug:slug>/architecture/generate/",
        ArchitectureGenerateView.as_view(),
        name="architecture-generate",
    ),
    path(
        "projects/<slug:slug>/architecture/",
        ArchitectureUpdateView.as_view(),
        name="architecture-update",
    ),
    path(
        "projects/<slug:slug>/architecture/approve/",
        ArchitectureApproveView.as_view(),
        name="architecture-approve",
    ),
    path(
        "projects/<slug:slug>/roadmap/generate/",
        RoadmapGenerateView.as_view(),
        name="roadmap-generate",
    ),
    path(
        "projects/<slug:slug>/roadmap/",
        RoadmapUpdateView.as_view(),
        name="roadmap-update",
    ),
    path(
        "projects/<slug:slug>/roadmap/approve/",
        RoadmapApproveView.as_view(),
        name="roadmap-approve",
    ),
    path(
        "projects/<slug:slug>/roadmap/tasks/<str:task_id>/",
        RoadmapTaskView.as_view(),
        name="roadmap-task",
    ),
    path(
        "projects/<slug:slug>/roadmap/tasks/<str:task_id>/build-prompt/",
        BuildPromptGenerateView.as_view(),
        name="build-prompt-generate",
    ),
    path(
        "projects/<slug:slug>/roadmap/tasks/<str:task_id>/review-prompt/",
        ReviewPromptGenerateView.as_view(),
        name="review-prompt-generate",
    ),
    path(
        "projects/<slug:slug>/progress/",
        ProgressView.as_view(),
        name="project-progress",
    ),
    path(
        "projects/<slug:slug>/ship-checklist/",
        ShipChecklistView.as_view(),
        name="ship-checklist",
    ),
    path(
        "projects/<slug:slug>/conversations/",
        ConversationCreateView.as_view(),
        name="conversation-create",
    ),
    path(
        "projects/<slug:slug>/conversations/<uuid:conversation_id>/",
        ConversationDetailView.as_view(),
        name="conversation-detail",
    ),
    path(
        "projects/<slug:slug>/conversations/<uuid:conversation_id>/messages/",
        ConversationMessageView.as_view(),
        name="conversation-messages",
    ),
    path(
        "projects/<slug:slug>/proposals/<uuid:proposal_id>/approve/",
        ProposalApproveView.as_view(),
        name="proposal-approve",
    ),
    path(
        "projects/<slug:slug>/proposals/<uuid:proposal_id>/reject/",
        ProposalRejectView.as_view(),
        name="proposal-reject",
    ),
    # --- Data & Analytics (Phase I-1) ---
    path(
        "projects/<slug:slug>/data-brief/generate/",
        DataBriefGenerateView.as_view(),
        name="data-brief-generate",
    ),
    path(
        "projects/<slug:slug>/data-brief/",
        DataBriefUpdateView.as_view(),
        name="data-brief-update",
    ),
    path(
        "projects/<slug:slug>/data-brief/approve/",
        DataBriefApproveView.as_view(),
        name="data-brief-approve",
    ),
    path(
        "projects/<slug:slug>/datasets/",
        DatasetListCreateView.as_view(),
        name="dataset-list-create",
    ),
    path(
        "projects/<slug:slug>/datasets/<uuid:dataset_id>/",
        DatasetDetailView.as_view(),
        name="dataset-detail",
    ),
    path(
        "projects/<slug:slug>/datasets/<uuid:dataset_id>/profile/",
        DatasetProfileView.as_view(),
        name="dataset-profile",
    ),
    path(
        "projects/<slug:slug>/datasets/<uuid:dataset_id>/interpret/",
        SourceInterpretationGenerateView.as_view(),
        name="source-interpretation-generate",
    ),
    path(
        "projects/<slug:slug>/datasets/<uuid:dataset_id>/interpretation/",
        SourceInterpretationUpdateView.as_view(),
        name="source-interpretation-update",
    ),
    path(
        "projects/<slug:slug>/datasets/<uuid:dataset_id>/interpret/approve/",
        SourceInterpretationApproveView.as_view(),
        name="source-interpretation-approve",
    ),
    path(
        "projects/<slug:slug>/jobs/<uuid:job_id>/",
        JobDetailView.as_view(),
        name="job-detail",
    ),
    # --- Data Quality (Phase I-2) ---
    path(
        "projects/<slug:slug>/data-quality/",
        DataQualityView.as_view(),
        name="data-quality",
    ),
    path(
        "projects/<slug:slug>/data-quality/observe/",
        DataQualityObserveView.as_view(),
        name="data-quality-observe",
    ),
    path(
        "projects/<slug:slug>/data-quality/propose-rules/",
        DataQualityProposeRulesView.as_view(),
        name="data-quality-propose-rules",
    ),
    path(
        "projects/<slug:slug>/data-quality/approve/",
        DataQualityApproveView.as_view(),
        name="data-quality-approve",
    ),
    path(
        "projects/<slug:slug>/data-quality/check/",
        DataQualityCheckView.as_view(),
        name="data-quality-check",
    ),
    # --- Transformation Plan (Phase I-2) ---
    path(
        "projects/<slug:slug>/transformation/",
        TransformationView.as_view(),
        name="transformation",
    ),
    path(
        "projects/<slug:slug>/transformation/generate/",
        TransformationGenerateView.as_view(),
        name="transformation-generate",
    ),
    path(
        "projects/<slug:slug>/transformation/approve/",
        TransformationApproveView.as_view(),
        name="transformation-approve",
    ),
    path(
        "projects/<slug:slug>/transformation/preview/",
        TransformationPreviewView.as_view(),
        name="transformation-preview",
    ),
    # --- Metrics / KPIs (Phase I-3) ---
    path(
        "projects/<slug:slug>/metrics/",
        MetricListView.as_view(),
        name="metric-list",
    ),
    path(
        "projects/<slug:slug>/metrics/generate/",
        MetricGenerateView.as_view(),
        name="metric-generate",
    ),
    path(
        "projects/<slug:slug>/metrics/<uuid:metric_id>/",
        MetricDetailView.as_view(),
        name="metric-detail",
    ),
    path(
        "projects/<slug:slug>/metrics/<uuid:metric_id>/approve/",
        MetricApproveView.as_view(),
        name="metric-approve",
    ),
    path(
        "projects/<slug:slug>/metrics/<uuid:metric_id>/validate/",
        MetricValidateView.as_view(),
        name="metric-validate",
    ),
    # --- Queries (Phase I-3) ---
    path(
        "projects/<slug:slug>/queries/",
        QueryListCreateView.as_view(),
        name="query-list-create",
    ),
    path(
        "projects/<slug:slug>/queries/<uuid:query_id>/",
        QueryDetailView.as_view(),
        name="query-detail",
    ),
    path(
        "projects/<slug:slug>/queries/<uuid:query_id>/plan/",
        QueryPlanUpdateView.as_view(),
        name="query-plan-update",
    ),
    path(
        "projects/<slug:slug>/queries/<uuid:query_id>/approve-plan/",
        QueryPlanApproveView.as_view(),
        name="query-plan-approve",
    ),
    path(
        "projects/<slug:slug>/queries/<uuid:query_id>/generate-sql/",
        QueryGenerateSqlView.as_view(),
        name="query-generate-sql",
    ),
    path(
        "projects/<slug:slug>/queries/<uuid:query_id>/review/",
        QueryReviewView.as_view(),
        name="query-review",
    ),
    path(
        "projects/<slug:slug>/queries/<uuid:query_id>/mark-reviewed/",
        QueryMarkReviewedView.as_view(),
        name="query-mark-reviewed",
    ),
    path(
        "projects/<slug:slug>/queries/<uuid:query_id>/execute/",
        QueryExecuteView.as_view(),
        name="query-execute",
    ),
    # --- Data Lineage (Phase I-3) ---
    path(
        "projects/<slug:slug>/lineage/",
        DataLineageView.as_view(),
        name="data-lineage",
    ),
    # --- Analysis Plans (Phase I-4) ---
    path(
        "projects/<slug:slug>/analysis/plans/",
        AnalysisPlanListCreateView.as_view(),
        name="analysis-plan-list-create",
    ),
    path(
        "projects/<slug:slug>/analysis/plans/generate/",
        AnalysisPlanGenerateView.as_view(),
        name="analysis-plan-generate",
    ),
    path(
        "projects/<slug:slug>/analysis/plans/<uuid:plan_id>/",
        AnalysisPlanDetailView.as_view(),
        name="analysis-plan-detail",
    ),
    path(
        "projects/<slug:slug>/analysis/plans/<uuid:plan_id>/approve/",
        AnalysisPlanApproveView.as_view(),
        name="analysis-plan-approve",
    ),
    path(
        "projects/<slug:slug>/analysis/plans/<uuid:plan_id>/run/",
        AnalysisPlanRunView.as_view(),
        name="analysis-plan-run",
    ),
    # --- Analysis Results / Insights (Phase I-4) ---
    path(
        "projects/<slug:slug>/analysis/results/<uuid:result_id>/",
        AnalysisResultDetailView.as_view(),
        name="analysis-result-detail",
    ),
    path(
        "projects/<slug:slug>/analysis/results/<uuid:result_id>/insights/generate/",
        InsightGenerateView.as_view(),
        name="insight-generate",
    ),
    path(
        "projects/<slug:slug>/analysis/insights/<uuid:insight_id>/accept/",
        InsightAcceptView.as_view(),
        name="insight-accept",
    ),
    # --- Dashboard Blueprint (Phase I-4) ---
    path(
        "projects/<slug:slug>/dashboard/",
        DashboardView.as_view(),
        name="dashboard",
    ),
    path(
        "projects/<slug:slug>/dashboard/generate/",
        DashboardGenerateView.as_view(),
        name="dashboard-generate",
    ),
    path(
        "projects/<slug:slug>/dashboard/approve/",
        DashboardApproveView.as_view(),
        name="dashboard-approve",
    ),
    path(
        "projects/<slug:slug>/dashboard/build-prompt/",
        DashboardBuildPromptView.as_view(),
        name="dashboard-build-prompt",
    ),
    # --- Data Progress / Delivery Readiness (Phase I-5) ---
    path(
        "projects/<slug:slug>/data-progress/",
        DataProgressView.as_view(),
        name="data-progress",
    ),
    path(
        "projects/<slug:slug>/data-readiness/",
        DataReadinessView.as_view(),
        name="data-readiness",
    ),
]

