# Generated by Django 5.1.4 on 2026-08-28 18:45

import projects.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(default=projects.models.generate_slug, editable=False, max_length=32, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('original_idea', models.TextField()),
                ('stage', models.CharField(choices=[('discovery', 'Discovery'), ('blueprint', 'Blueprint'), ('architecture', 'Architecture'), ('roadmap', 'Roadmap'), ('building', 'Building'), ('ship', 'Ship')], default='discovery', max_length=20)),
                ('discovery', models.JSONField(blank=True, default=dict)),
                ('context_digest', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
