# Generated by Django 5.1.4 on 2026-08-28 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='blueprint',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='project',
            name='blueprint_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
