# Generated by Django 5.1.4 on 2026-08-28 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_blueprint_project_blueprint_approved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='architecture',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='project',
            name='architecture_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
