# Generated by Django 5.1.4 on 2026-08-28 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_architecture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='roadmap',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='project',
            name='roadmap_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
