# Generated by Django 5.1.4 on 2026-08-28 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_roadmap_project_roadmap_approved_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=16)),
                ('task_title', models.CharField(blank=True, max_length=300)),
                ('kind', models.CharField(choices=[('build', 'Build'), ('review', 'Review')], default='build', max_length=8)),
                ('content', models.TextField()),
                ('context_snapshot', models.JSONField(default=dict)),
                ('model', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'task_id', '-created_at'], name='projects_ge_project_a6ed7c_idx')],
            },
        ),
    ]
