# Generated by Django 5.1.4 on 2026-09-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_generatedprompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='downstream_stale',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('software', 'Software'), ('data', 'Data & Analytics')], default='software', max_length=16),
        ),
    ]
