# Generated by Django 5.1.4 on 2026-09-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_downstream_stale_project_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='business_logic',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='project',
            name='business_logic_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='stage',
            field=models.CharField(choices=[('discovery', 'Discovery'), ('blueprint', 'Blueprint'), ('business_logic', 'Business Logic'), ('architecture', 'Architecture'), ('roadmap', 'Roadmap'), ('building', 'Building'), ('ship', 'Ship')], default='discovery', max_length=20),
        ),
    ]
