# Generated by Django 5.1.4 on 2026-09-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_business_logic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ship_checklist',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
