# Generated by Django 5.1.4 on 2026-09-10 13:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_conversation_conversationmessage_proposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='data_brief',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='project',
            name='data_brief_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='data_goal',
            field=models.CharField(blank=True, choices=[('analytics', 'Analytics'), ('bi', 'BI / Dashboards'), ('engineering', 'Data Engineering'), ('warehouse', 'Warehouse / Marts'), ('quality', 'Data Quality'), ('mixed', 'Mixed')], default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='project',
            name='stage',
            field=models.CharField(choices=[('discovery', 'Discovery'), ('blueprint', 'Blueprint'), ('business_logic', 'Business Logic'), ('architecture', 'Architecture'), ('roadmap', 'Roadmap'), ('building', 'Building'), ('ship', 'Ship'), ('data_brief', 'Data Brief'), ('data_sources', 'Data Sources')], default='discovery', max_length=32),
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('source_type', models.CharField(choices=[('csv', 'CSV'), ('json', 'JSON')], max_length=8)),
                ('storage_ref', models.CharField(max_length=500)),
                ('original_filename', models.CharField(blank=True, max_length=300)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('encoding', models.CharField(blank=True, max_length=32, null=True)),
                ('delimiter', models.CharField(blank=True, max_length=4, null=True)),
                ('row_count', models.IntegerField(blank=True, null=True)),
                ('column_count', models.IntegerField(blank=True, null=True)),
                ('inferred_schema', models.JSONField(blank=True, default=list)),
                ('sampled', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('profiling', 'Profiling'), ('profiled', 'Profiled'), ('failed', 'Failed')], default='uploaded', max_length=12)),
                ('profiling_stale', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
                ('interpretation', models.JSONField(blank=True, default=dict)),
                ('interpretation_approved_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('profiled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='projects.project')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='projects.dataset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('profile_dataset', 'Profile dataset')], max_length=32)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=12)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('result_ref', models.JSONField(blank=True, default=dict)),
                ('progress', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='projects.dataset')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfilingRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('table_stats', models.JSONField(default=dict)),
                ('columns', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiling_runs', to='projects.dataset')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiling_runs', to='projects.job')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='dataset',
            index=models.Index(fields=['project', '-created_at'], name='projects_da_project_06e099_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['project', '-created_at'], name='projects_jo_project_4792be_idx'),
        ),
    ]
