# Generated by Django 5.1.4 on 2026-09-10 13:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_project_data_brief_project_data_brief_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='data_quality',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='project',
            name='data_quality_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='transformation_plan',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='project',
            name='transformation_plan_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='kind',
            field=models.CharField(choices=[('profile_dataset', 'Profile dataset'), ('run_quality_checks', 'Run quality checks'), ('run_transformation_preview', 'Run transformation preview')], max_length=32),
        ),
        migrations.CreateModel(
            name='QualityCheckRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('results', models.JSONField(default=list)),
                ('summary', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_check_runs', to='projects.job')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_check_runs', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
