# Generated by Django 5.1.4 on 2026-09-11 13:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_project_data_quality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='kind',
            field=models.CharField(choices=[('profile_dataset', 'Profile dataset'), ('run_quality_checks', 'Run quality checks'), ('run_transformation_preview', 'Run transformation preview'), ('validate_metric', 'Validate metric'), ('execute_query', 'Execute query')], max_length=32),
        ),
        migrations.CreateModel(
            name='MetricDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_id', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=200)),
                ('business_meaning', models.TextField(blank=True, default='')),
                ('formula_text', models.TextField(blank=True, default='')),
                ('structured', models.JSONField(default=dict)),
                ('time_grain', models.CharField(blank=True, default='', max_length=16)),
                ('allowed_dimensions', models.JSONField(blank=True, default=list)),
                ('source_fields', models.JSONField(blank=True, default=list)),
                ('owner', models.CharField(blank=True, default='', max_length=200)),
                ('related_goal_ref', models.CharField(blank=True, default='', max_length=64)),
                ('caveats', models.JSONField(blank=True, default=list)),
                ('validation_checks', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved')], default='draft', max_length=12)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='projects.project')),
            ],
            options={
                'ordering': ['business_id'],
            },
        ),
        migrations.CreateModel(
            name='MetricValidationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query_sql', models.TextField(blank=True, default='')),
                ('result', models.JSONField(blank=True, default=dict)),
                ('passed', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metric_validation_runs', to='projects.job')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_runs', to='projects.metricdefinition')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_id', models.CharField(max_length=16)),
                ('question', models.TextField()),
                ('plan', models.JSONField(blank=True, default=dict)),
                ('plan_approved_at', models.DateTimeField(blank=True, null=True)),
                ('sql', models.TextField(blank=True, default='')),
                ('dialect', models.CharField(default='duckdb', max_length=16)),
                ('kpi_refs', models.JSONField(blank=True, default=list)),
                ('review', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft_plan', 'Draft plan'), ('plan_approved', 'Plan approved'), ('sql_generated', 'SQL generated'), ('reviewed', 'Reviewed'), ('executed', 'Executed')], default='draft_plan', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_run_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.job')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='projects.project')),
            ],
            options={
                'ordering': ['business_id'],
            },
        ),
        migrations.CreateModel(
            name='QueryRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('executed_sql', models.TextField()),
                ('columns', models.JSONField(default=list)),
                ('rows', models.JSONField(default=list)),
                ('row_count', models.IntegerField(default=0)),
                ('truncated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.job')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='projects.query')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='metricdefinition',
            constraint=models.UniqueConstraint(fields=('project', 'business_id'), name='unique_metric_business_id'),
        ),
        migrations.AddConstraint(
            model_name='query',
            constraint=models.UniqueConstraint(fields=('project', 'business_id'), name='unique_query_business_id'),
        ),
    ]
