# Generated by Django 5.1.4 on 2026-09-11 15:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_job_kind_metricdefinition_metricvalidationrun_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='dashboard_blueprint',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='project',
            name='dashboard_blueprint_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='kind',
            field=models.CharField(choices=[('profile_dataset', 'Profile dataset'), ('run_quality_checks', 'Run quality checks'), ('run_transformation_preview', 'Run transformation preview'), ('validate_metric', 'Validate metric'), ('execute_query', 'Execute query'), ('run_analysis', 'Run analysis')], max_length=32),
        ),
        migrations.CreateModel(
            name='AnalysisPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_id', models.CharField(max_length=16)),
                ('business_question', models.TextField()),
                ('hypotheses', models.JSONField(blank=True, default=list)),
                ('required_metrics', models.JSONField(blank=True, default=list)),
                ('segments', models.JSONField(blank=True, default=list)),
                ('comparisons', models.JSONField(blank=True, default=list)),
                ('time_range', models.JSONField(blank=True, default=dict)),
                ('method', models.CharField(choices=[('descriptive', 'Descriptive'), ('trend', 'Trend'), ('segmentation', 'Segmentation'), ('comparison', 'Comparison'), ('funnel', 'Funnel')], max_length=16)),
                ('expected_outputs', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved')], default='draft', max_length=12)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_plans', to='projects.project')),
            ],
            options={
                'ordering': ['business_id'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('findings', models.JSONField(default=list)),
                ('data_caveats', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.job')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='projects.analysisplan')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DashboardBuildPrompt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('context_snapshot', models.JSONField(default=dict)),
                ('model', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_build_prompts', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_id', models.CharField(max_length=16)),
                ('fact', models.TextField()),
                ('interpretation', models.TextField(blank=True, default='')),
                ('recommendation', models.TextField(blank=True, default='')),
                ('confidence', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=8)),
                ('supporting_finding_ids', models.JSONField(default=list)),
                ('caveats', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('accepted', 'Accepted')], default='draft', max_length=10)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='projects.analysisresult')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='projects.project')),
            ],
            options={
                'ordering': ['business_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='analysisplan',
            constraint=models.UniqueConstraint(fields=('project', 'business_id'), name='unique_analysis_plan_business_id'),
        ),
        migrations.AddConstraint(
            model_name='insight',
            constraint=models.UniqueConstraint(fields=('project', 'business_id'), name='unique_insight_business_id'),
        ),
    ]
