# Generated by Django 5.1.4 on 2026-09-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_project_dashboard_blueprint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisplan',
            name='stale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='analysisplan',
            name='stale_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='analysisplan',
            name='stale_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='interpretation_stale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='metricdefinition',
            name='stale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='metricdefinition',
            name='stale_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='metricdefinition',
            name='stale_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='data_readiness',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='query',
            name='stale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='query',
            name='stale_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='query',
            name='stale_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
