# Generated by Django 5.1.4 on 2026-09-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airequestlog',
            name='prompt_version',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='airequestlog',
            name='provider',
            field=models.CharField(default='anthropic', max_length=32),
        ),
    ]
